data:
  path: data
  dataset_files:
  - label: data/train_set.ReorgE.csv
    structures: data/mol_files/train_set
  # - label: data/test_set.csv
  #   structures: data/mol_files/test_set
  max_length: 160
  bond_drop_prob: 0.1
  num_folds: 5
  fold_index: 0
  dataloader_workers: 4

model:
  random_seed: 42
  pretrained_model_path: 
  # smile_model_name: pchanda/pretrained-smiles-pubchem10m

  # num_layers: 12
  hidden_dim: 256
  # intermediate_dim: 3072
  # num_attention_heads: 12
  # hidden_dropout_prob: 0.1
  # attention_dropout_prob: 0.1
  # position_scale: 100.0
  # initialize_range: 0.02

train:
  name: dimenet++
  optimizer:
    lr: 1e-5
    betas: [0.9, 0.999]
    eps: 1e-6
    weight_decay: 0.01
  epochs: 20
  warmup_ratio: 0.1
  batch_size: 16
  accumulate_grads: 4
  max_grad_norm: 0.5
  validation_interval: 0.5
  precision: 32
  gpus: 1

infer:

  # predict_from: mot-finetuning/2zjgyv7h
  predict_from: mot-finetuning/2zjgyv7h/checkpoints/epoch=16-step=8990.ckpt
  filename: 2zjgyv7h.csv